public class code389 {
    /*
    Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
     */
    public char findTheDifference(String s, String t) {
        int[] count_s = new int[26];
        int[] count_t = new int[26];
        for(char c:s.toCharArray()){
            count_s[c-'a']++;
        }
        for(char c:t.toCharArray()){
            count_t[c-'a']++;
        }
        char res = 'a';
        for(int i=0;i<26;i++){
            if(count_t[i]!=count_s[i]){
                res +=i;
            }
        }
        return res;
    }
}
